CREATE PROCEDURE p_id_vendedor
@ID_USER nvarchar(50),
@ID_PRODUCTO int,
@FK_ESCUELA int,
@FK_CATEGORIA nvarchar(100),
@NOMBRE nvarchar(50),
@DESCRIPCION nvarchar(255),
@IMG nvarchar(50),
@STOCK int,
@PRECIO float
AS
DECLARE @idRand INT;
DECLARE @FK_VENDEDOR INT;
DECLARE @ESC NVARCHAR(25);
SET @idRand = FLOOR(RAND()*(1000-1)+1);
SET @ESC = (SELECT NOMBRE FROM Escuela WHERE ID_ESCUELA =@FK_ESCUELA);
IF NOT EXISTS(SELECT * FROM Vendedor WHERE FK_USER=@ID_USER)
    BEGIN
      INSERT INTO Vendedor(FK_USER, ID_VENDEDOR,NC) 
      VALUES (@ID_USER,@idRand,@ID_USER +' '+@ESC);
	  SET @FK_VENDEDOR = (SELECT ID_VENDEDOR FROM Vendedor WHERE FK_USER =@ID_USER);
	  INSERT INTO Producto VALUES(@ID_PRODUCTO,@FK_VENDEDOR,@FK_ESCUELA,@FK_CATEGORIA,@NOMBRE,@DESCRIPCION,@IMG,@STOCK,1,@PRECIO);
    END
  ELSE 
    BEGIN
	SET @FK_VENDEDOR = (SELECT ID_VENDEDOR FROM Vendedor WHERE FK_USER =@ID_USER);
	INSERT INTO Producto VALUES(@ID_PRODUCTO,@FK_VENDEDOR,@FK_ESCUELA,@FK_CATEGORIA,@NOMBRE,@DESCRIPCION,@IMG,@STOCK,1,@PRECIO);
    END

EXEC p_id_vendedor 'Jessy',38,23,'Practicas','Arduino Mega','Chido','ard.jpg',2,150;
