CREATE PROCEDURE p_id_vendedor

@ID_USER nvarchar(50),
@SRV int,
@ID_PRODUCTO int,
@FK_ESCUELA int,
@FK_CATEGORIA nvarchar(100),
@NOMBRE nvarchar(50),
@DESCRIPCION nvarchar(255),
@IMG nvarchar(50),
@STOCK int,
@PRECIO float

AS

DECLARE @idRand INT;
DECLARE @FK_VENDEDOR INT;
DECLARE @ESC NVARCHAR(25);
SET @idRand = FLOOR(RAND()*(1000-1)+1);
SET @ESC = (SELECT NOMBRE FROM Escuela WHERE ID_ESCUELA =@FK_ESCUELA);

IF NOT EXISTS(SELECT * FROM S1.B.dbo.Vendedor WHERE FK_USER=@ID_USER)
    BEGIN

      INSERT INTO Vendedor(FK_USER, ID_VENDEDOR,NC) 
      VALUES (@ID_USER,@idRand,@ID_USER +' '+@ESC);

	  INSERT INTO S2.B.dbo.Vendedor(FK_USER, ID_VENDEDOR,NC) 
      VALUES (@ID_USER,@idRand,@ID_USER +' '+@ESC);

	  INSERT INTO S3.B.dbo.Vendedor(FK_USER, ID_VENDEDOR,NC) 
      VALUES (@ID_USER,@idRand,@ID_USER +' '+@ESC);


	  SET @FK_VENDEDOR = (SELECT ID_VENDEDOR FROM Vendedor WHERE FK_USER =@ID_USER);

	  IF @SRV=1
	  BEGIN
	  INSERT INTO Producto VALUES(@ID_PRODUCTO,@FK_VENDEDOR,@FK_ESCUELA,@FK_CATEGORIA,@NOMBRE,@DESCRIPCION,@IMG,@STOCK,1,@PRECIO);
	  END
	  IF @SRV=2
	  BEGIN
	  INSERT INTO S2.B.dbo.Producto VALUES(@ID_PRODUCTO,@FK_VENDEDOR,@FK_ESCUELA,@FK_CATEGORIA,@NOMBRE,@DESCRIPCION,@IMG,@STOCK,1,@PRECIO);
	  END
	  IF @SRV=3
	  BEGIN
	  INSERT INTO S3.B.dbo.Producto VALUES(@ID_PRODUCTO,@FK_VENDEDOR,@FK_ESCUELA,@FK_CATEGORIA,@NOMBRE,@DESCRIPCION,@IMG,@STOCK,1,@PRECIO);
	  END
    END
  ELSE 
    BEGIN
	SET @FK_VENDEDOR = (SELECT ID_VENDEDOR FROM Vendedor WHERE FK_USER =@ID_USER);
	IF @SRV = 1
	BEGIN
	INSERT INTO Producto VALUES(@ID_PRODUCTO,@FK_VENDEDOR,@FK_ESCUELA,@FK_CATEGORIA,@NOMBRE,@DESCRIPCION,@IMG,@STOCK,1,@PRECIO);
	END
	IF @SRV = 2
	BEGIN
	INSERT INTO S2.B.dbo.Producto VALUES(@ID_PRODUCTO,@FK_VENDEDOR,@FK_ESCUELA,@FK_CATEGORIA,@NOMBRE,@DESCRIPCION,@IMG,@STOCK,1,@PRECIO);
	END
	IF @SRV = 3
	BEGIN
	INSERT INTO S3.B.dbo.Producto VALUES(@ID_PRODUCTO,@FK_VENDEDOR,@FK_ESCUELA,@FK_CATEGORIA,@NOMBRE,@DESCRIPCION,@IMG,@STOCK,1,@PRECIO);
	END
    END 