--Proceso para Publicar
CREATE PROCEDURE p_id_vendedor
@ID_USER nvarchar(50),
@ID_PRODUCTO int,
@FK_ESCUELA int,
@FK_CATEGORIA nvarchar(100),
@NOMBRE nvarchar(50),
@DESCRIPCION nvarchar(255),
@IMG nvarchar(50),
@STOCK int,
@PRECIO float
AS
DECLARE @idRand INT;
DECLARE @FK_VENDEDOR INT;
DECLARE @ESC NVARCHAR(25);
SET @idRand = FLOOR(RAND()*(1000-1)+1);
SET @ESC = (SELECT NOMBRE FROM Escuela WHERE ID_ESCUELA =@FK_ESCUELA);
IF NOT EXISTS(SELECT * FROM Vendedor WHERE FK_USER=@ID_USER)
    BEGIN
      INSERT INTO Vendedor(FK_USER, ID_VENDEDOR,NC) 
      VALUES (@ID_USER,@idRand,@ID_USER +' '+@ESC);
	  SET @FK_VENDEDOR = (SELECT ID_VENDEDOR FROM Vendedor WHERE FK_USER =@ID_USER);
	  INSERT INTO Producto VALUES(@ID_PRODUCTO,@FK_VENDEDOR,@FK_ESCUELA,@FK_CATEGORIA,@NOMBRE,@DESCRIPCION,@IMG,@STOCK,1,@PRECIO);
    END
  ELSE 
    BEGIN
	SET @FK_VENDEDOR = (SELECT ID_VENDEDOR FROM Vendedor WHERE FK_USER =@ID_USER);
	INSERT INTO Producto VALUES(@ID_PRODUCTO,@FK_VENDEDOR,@FK_ESCUELA,@FK_CATEGORIA,@NOMBRE,@DESCRIPCION,@IMG,@STOCK,1,@PRECIO);
    END

EXEC p_id_vendedor 'Jessy',38,23,'Practicas','Arduino Mega','Chido','ard.jpg',2,150;
-- Proceso para ACTULIZAR PRODUCTO SERVER 1
CREATE PROCEDURE acualizar_publicacion
@SRV INT,
@ID_PRODUCTO INT,
@FK_ESCUELA INT,
@FK_CATEGORIA NVARCHAR(100),
@NOMBRE NVARCHAR(50),
@DESCRIPCION NVARCHAR(255),
@STOCK INT,
@STATUS BIT,
@PRECIO FLOAT
AS

IF @SRV = 1
BEGIN
UPDATE Producto SET FK_CATEGORIA=@FK_CATEGORIA, FK_ESCUELA=@FK_ESCUELA,
NOMBRE=@NOMBRE,DESCRIPCION=@DESCRIPCION, STOCK=@STOCK, STATUS=@STATUS,PRECIO=@PRECIO
WHERE ID_PRODUCTO=@ID_PRODUCTO;
END
ELSE
BEGIN
UPDATE Producto SET FK_CATEGORIA=@FK_CATEGORIA, FK_ESCUELA=@FK_ESCUELA,
NOMBRE=@NOMBRE,DESCRIPCION=@DESCRIPCION, STOCK=@STOCK, STATUS=@STATUS,PRECIO=@PRECIO
WHERE ID_PRODUCTO=@ID_PRODUCTO;
INSERT INTO S2.B.dbo.Producto 
SELECT * FROM Producto WHERE ID_PRODUCTO = @ID_PRODUCTO
INSERT INTO S2.B.dbo.Compras
SELECT * FROM Compras WHERE FK_PRODUCTO = @ID_PRODUCTO
DELETE Compras WHERE FK_PRODUCTO= @ID_PRODUCTO
DELETE Producto WHERE ID_PRODUCTO= @ID_PRODUCTO
END



-- Proceso para ACTULIZAR PRODUCTO SERVER 2
CREATE PROCEDURE acualizar_publicacion
@SRV INT,
@ID_PRODUCTO INT,
@FK_ESCUELA INT,
@FK_CATEGORIA NVARCHAR(100),
@NOMBRE NVARCHAR(50),
@DESCRIPCION NVARCHAR(255),
@STOCK INT,
@STATUS BIT,
@PRECIO FLOAT
AS

IF @SRV = 2
BEGIN
UPDATE Producto SET FK_CATEGORIA=@FK_CATEGORIA, FK_ESCUELA=@FK_ESCUELA,
NOMBRE=@NOMBRE,DESCRIPCION=@DESCRIPCION, STOCK=@STOCK, STATUS=@STATUS,PRECIO=@PRECIO
WHERE ID_PRODUCTO=@ID_PRODUCTO;
END
ELSE
BEGIN
UPDATE Producto SET FK_CATEGORIA=@FK_CATEGORIA, FK_ESCUELA=@FK_ESCUELA,
NOMBRE=@NOMBRE,DESCRIPCION=@DESCRIPCION, STOCK=@STOCK, STATUS=@STATUS,PRECIO=@PRECIO
WHERE ID_PRODUCTO=@ID_PRODUCTO;
INSERT INTO S1.B.dbo.Producto 
SELECT * FROM Producto WHERE ID_PRODUCTO = @ID_PRODUCTO
INSERT INTO S1.B.dbo.Compras
SELECT * FROM Compras WHERE FK_PRODUCTO = @ID_PRODUCTO
DELETE Compras WHERE FK_PRODUCTO= @ID_PRODUCTO
DELETE Producto WHERE ID_PRODUCTO= @ID_PRODUCTO
END