--GetProduct
SELECT 
        ID_PRODUCTO, T1.FK_USER AS FK_VENDEDOR, T2.NOMBRE AS FK_ESCUELA,FK_CATEGORIA,T.NOMBRE,DESCRIPCION,IMG,STOCK,STATUS,PRECIO 
        FROM Producto AS T
        INNER JOIN
        Vendedor AS T1
        ON T.FK_VENDEDOR = T1.ID_VENDEDOR
        INNER JOIN Escuela AS T2 
        ON T.FK_ESCUELA = T2.ID_ESCUELA;
--        
SELECT 
        ID_PRODUCTO, T1.FK_USER AS FK_VENDEDOR, T2.NOMBRE AS FK_ESCUELA,FK_CATEGORIA,T.NOMBRE,DESCRIPCION,IMG,STOCK,STATUS,PRECIO 
        FROM Producto AS T
        INNER JOIN
        Vendedor AS T1
        ON T.FK_VENDEDOR = T1.ID_VENDEDOR
        INNER JOIN Escuela AS T2 
        ON T.FK_ESCUELA = T2.ID_ESCUELA
        WHERE ID_PRODUCT=O43234
--
SELECT 
    ID_PRODUCTO, T1.FK_USER AS FK_VENDEDOR, T2.NOMBRE AS FK_ESCUELA,FK_CATEGORIA,T.NOMBRE,DESCRIPCION,IMG,STOCK,STATUS,PRECIO 
    FROM Producto AS T
    INNER JOIN
    Vendedor AS T1
    ON T.FK_VENDEDOR = T1.ID_VENDEDOR
    INNER JOIN Escuela AS T2 
    ON T.FK_ESCUELA = T2.ID_ESCUELA
    WHERE FK_CATEGORIA='Electronica'
--
SELECT * FROM Producto
WHERE PRECIO >= 2 AND PRECIO <= 2

--

SELECT 
        ID_PRODUCTO, T1.FK_USER AS FK_VENDEDOR, T2.NOMBRE AS FK_ESCUELA,FK_CATEGORIA,T.NOMBRE,DESCRIPCION,IMG,STOCK,STATUS,PRECIO 
        FROM Producto AS T
        INNER JOIN
        Vendedor AS T1
        ON T.FK_VENDEDOR = T1.ID_VENDEDOR
        INNER JOIN Escuela AS T2 
        ON T.FK_ESCUELA = T2.ID_ESCUELA
        WHERE FK_CATEGORIA='Electronica' AND T2.NOMBRE='UPIITA'